#[module]
#    proxy = 'https://goproxy.cn'
#
#theme = "github.com/razonyang/hugo-theme-bootstrap"

baseURL = 'https://example.com'
languageCode = 'en-us'
title = 'YCP Hacks Documentation'
theme = "ananke"